batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 4
model_path: Models/03_handwriting_recognition/202312101620
train_epochs: 1
train_workers: 20
vocab: 2QKBRgbaf43eNc+781d#xh65
width: 128
