batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312101423
train_epochs: 1000
train_workers: 20
vocab: fB354d+6QbK8ONc17eR#-gxha2
width: 128
