batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102358
train_epochs: 10
train_workers: 20
vocab: hx53ea6f8+b#2gONK1-B7Q4Rcd
width: 128
