batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102347
train_epochs: 100
train_workers: 20
vocab: eO#73c5f+Rh6NBQ8g4a2-1xKbd
width: 128
