batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312101543
train_epochs: 15
train_workers: 20
vocab: '#KNebdfR-2x68cQ51BOah7g43+'
width: 128
