batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312101545
train_epochs: 15
train_workers: 20
vocab: Oe17KgN3bQ5dfR2xa4#8+Bch6-
width: 128
