batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312101556
train_epochs: 1
train_workers: 20
vocab: R2#6QOc5Bhe+Nga7-8fbd4x1K3
width: 128
