batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102233
train_epochs: 100
train_workers: 20
vocab: 7x-f4Bb#d23Ke1h6ONa5=8gRQ+c
width: 128
