batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102349
train_epochs: 10
train_workers: 40
vocab: a7Nf-ge4xK82hORdc#Q3+5B1b6
width: 128
