batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312110019
train_epochs: 10
train_workers: 20
vocab: cO6b-da2he+174K3#gQ8fBxNR5
width: 128
