batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312120719
train_epochs: 50
train_workers: 20
vocab: 2#OeNQd3Bx54g6178+bcK=fahR-
width: 128
