batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312111306
train_epochs: 10
train_workers: 20
vocab: '#RO=fh3bg1-dxa6N+cBe254Q8K7'
width: 128
