batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102230
train_epochs: 10
train_workers: 20
vocab: 5b84ca36BOhdfxgK+=NQ-2e1#7R
width: 128
