batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312111026
train_epochs: 10
train_workers: 20
vocab: c3B587hNf#Rd=-x61geO24abK+Q
width: 128
