batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312111633
train_epochs: 10
train_workers: 20
vocab: cNbed457fg-8aB#62KOQh1=R3+x
width: 128
