batch_size: 32
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312102353
train_epochs: 10
train_workers: 40
vocab: gO1eB2+c64hK-Q358fda7R#Nbx
width: 128
