batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312111020
train_epochs: 10
train_workers: 20
vocab: -2QxadR1f4ONe+c736K#h=gb8B5
width: 128
