batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 5
model_path: Models/03_handwriting_recognition/202312110011
train_epochs: 10
train_workers: 20
vocab: b2g3N-8af4+Ode#KBR7c1Qx65h
width: 128
