batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 4
model_path: Models/03_handwriting_recognition/202312101619
train_epochs: 1
train_workers: 20
vocab: +6KBc38ef4RN2gQh57adb#1x
width: 128
